# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  pathToSolution: 'WhatYouGot/'

steps:

# add Sonar Cloud prepare task

# add dot net build script
- script:
    dotnet build --configuration $(buildConfiguration)
  workingDirectory: $(pathToSolution)
  displayName: 'dotnet build $(buildConfiguration)'

# add dot net test script

# add Sonar Cloud publish task

# add Sonar Cloud analyze task

# add .Net Core publish task

############ CI ends #############

############ CDevelopment starts ##########

# add Azure Web App task

############ CDevelopment ends ###########